# Generated by Django 3.2.9 on 2021-11-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facemask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaskCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('tela', models.CharField(max_length=30)),
            ],
        ),
    ]
