# Generated by Django 3.2.9 on 2021-11-13 23:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facemask', '0002_maskcreator'),
    ]

    operations = [
        migrations.AddField(
            model_name='maskcreator',
            name='color',
            field=models.CharField(choices=[('Azul', 'Azul'), ('Negro', 'Negro'), ('Rojo', 'Rojo'), ('Blanco', 'Blanco'), ('Gris', 'Gris'), ('Rosa', 'Rosa'), ('Cafe', 'Cafe')], default='Blanco', max_length=20),
        ),
        migrations.AddField(
            model_name='maskcreator',
            name='filtro',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='maskcreator',
            name='tela',
            field=models.CharField(choices=[('Algodón', 'Algodón'), ('Poliéster', 'Poliéster'), ('Franela', 'Franela'), ('Sábana', 'Sábana')], max_length=20),
        ),
    ]
