# Generated by Django 3.2.9 on 2021-11-14 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facemask', '0003_auto_20211113_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maskcreator',
            old_name='filtro',
            new_name='capas',
        ),
    ]
