# Generated by Django 3.2.9 on 2021-11-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facemask', '0004_rename_filtro_maskcreator_capas'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('asunto', models.CharField(max_length=100)),
                ('comment', models.TextField()),
            ],
        ),
    ]
